spring:
     profiles:
          active: test

---

spring:
     profiles: dev
     
msg: msg from dev

server:
     port: 9999

---

spring:
     profiles: prod

msg: msg from prod

server:
     port: 6666


          